/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package belajar.gradle

// import library
import com.google.gson.Gson
import kotlinx.coroutines.*
//import belajar.gradle.model.Product

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    val gson = Gson();
}

fun main() {
    println(App().greeting)

    println("Belajar Gradle Kotlin")

//    val product = Product()

}
